### PR TITLE
Make rename() POSIX-compatible. Fixes #91

### LINKED ISSUE #91: rename() behavior isn't POSIX-y enough.
C standard (N1570 7.21.4.2) states that

> The rename function causes the file whose name is the string pointed to by old to be henceforth known by the name given by the string pointed to by new. The file named old is no longer accessible by that name. **If a file named by the string pointed to by new exists prior to the call to the rename function, the behavior is implementation-defined**.

[posix](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html), [gcc](https://www.gnu.org/software/libc/manual/html_node/Renaming-Files.html) and [bsd](https://www.freebsd.org/cgi/man.cgi?query=rename) (see error ENOTEMPTY) state that if `to` exists, it shall be removed first, except if it is non-empty directory.

sceIoRename seems to follow MSVC implementation, e.g. fail if `to` exists,

Currently, this affects curl (cookie jar), but maybe other code/libs too.

### PR DESCRIPTION
**Pull request by isage**

### CODE REVIEW

File: newlib/libc/sys/vita/syscalls.c [hunk 1]
```diff
@@ -401,6 +401,17 @@ _rename_r(struct _reent *reent, const char *old, const char *new)
 		reent->_errno = errno; // set by realpath
 		return -1;
 	}
+
+	// sceIoRename fails if `new` exists.
+	// But to conform with POSIX/BSD, we should remove `new` if it's file or empty dir
+	ret = sceIoRemove(full_path_new);
+	if (ret == 0x80010015) // EISDIR
```
Comment (d3m3vilurr) [inline newlib/libc/sys/vita/syscalls.c:408]: can you make the enum in the vita-headers?
